/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadoraindicevegetacao;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author renan
 */
public class IndiceVegetacaoGUI extends javax.swing.JFrame {

    /**
     * Creates new form IndiceVegetacaoGUI
     */
    public IndiceVegetacaoGUI() {
        initComponents();
        getContentPane().setBackground(Color.DARK_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redField = new java.awt.TextField();
        nirField = new java.awt.TextField();
        btn = new java.awt.Button();
        redLabel = new java.awt.Label();
        labelqrq = new java.awt.Label();
        nirLabel = new java.awt.Label();
        resultNDVI = new java.awt.Label();
        resultSAVI = new java.awt.Label();
        resultRVI = new java.awt.Label();
        lField = new java.awt.TextField();
        llabel = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora De Indice de Vegetaçao @Renan !!!\nDesenvolvimento de Software I - @Diego Moraes");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        setForeground(java.awt.Color.black);
        setMinimumSize(new java.awt.Dimension(500, 280));
        setPreferredSize(new java.awt.Dimension(768, 250));
        setResizable(false);
        setSize(new java.awt.Dimension(580, 250));

        redField.setBackground(new java.awt.Color(51, 51, 51));
        redField.setForeground(new java.awt.Color(255, 255, 255));
        redField.setText("");
        redField.setBounds(140, 20, 120, 20);

        nirField.setBackground(new java.awt.Color(51, 51, 51));
        nirField.setForeground(new java.awt.Color(255, 255, 255));
        nirField.setText("");
        nirField.setBounds(140, 20, 120, 20);

        btn.setBackground(new java.awt.Color(102, 0, 0));
        btn.setFont(new java.awt.Font("Fira Code", 3, 14)); // NOI18N
        btn.setForeground(new java.awt.Color(200, 200, 200));
        btn.setLabel("Calcula-se");
        btn.setBounds(100, 80, 100, 30);
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        redLabel.setAlignment(java.awt.Label.CENTER);
        redLabel.setBackground(new java.awt.Color(255, 255, 255));
        redLabel.setForeground(new java.awt.Color(255, 0, 0));
        redLabel.setText("RED");
        redLabel.setBounds(20, 120, 250, 20);

        labelqrq.setAlignment(java.awt.Label.CENTER);
        labelqrq.setBackground(new java.awt.Color(1, 1, 1));
        labelqrq.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelqrq.setEnabled(false);
        labelqrq.setFont(new java.awt.Font("Fira Code Medium", 0, 14)); // NOI18N
        labelqrq.setForeground(new java.awt.Color(200, 200, 200));
        labelqrq.setMinimumSize(new java.awt.Dimension(78, 20));
        labelqrq.setPreferredSize(new java.awt.Dimension(380, 20));
        labelqrq.setText("RED(0,65 a 0,72), NIR (0,72 a 1,3) e L entre 0 e 1");
        //resultRVI.setBounds(20, 120, 250, 20);

        nirLabel.setAlignment(java.awt.Label.CENTER);
        nirLabel.setBackground(new java.awt.Color(255, 255, 255));
        nirLabel.setForeground(new java.awt.Color(255, 0, 0));
        nirLabel.setText("NIR");
        nirLabel.setBounds(20, 120, 250, 20);

        resultNDVI.setFont(new java.awt.Font("Fira Code Light", 2, 12)); // NOI18N
        resultNDVI.setForeground(new java.awt.Color(200, 200, 200));
        resultNDVI.setPreferredSize(new java.awt.Dimension(250, 20));
        resultNDVI.setText("");
        //resultNDVI.setBounds(20, 120, 250, 20);

        resultSAVI.setFont(new java.awt.Font("Fira Code Light", 2, 12)); // NOI18N
        resultSAVI.setForeground(new java.awt.Color(200, 200, 200));
        resultSAVI.setPreferredSize(new java.awt.Dimension(250, 20));
        resultSAVI.setText("");
        //resultSAVI.setBounds(20, 120, 250, 20);

        resultRVI.setFont(new java.awt.Font("Fira Code Light", 2, 12)); // NOI18N
        resultRVI.setForeground(new java.awt.Color(200, 200, 200));
        resultRVI.setMinimumSize(new java.awt.Dimension(78, 20));
        resultRVI.setPreferredSize(new java.awt.Dimension(250, 20));
        resultRVI.setText("");
        //resultRVI.setBounds(20, 120, 250, 20);

        lField.setBackground(new java.awt.Color(51, 51, 51));
        lField.setForeground(new java.awt.Color(255, 255, 255));
        lField.setText("");
        nirField.setBounds(140, 20, 120, 20);

        llabel.setAlignment(java.awt.Label.CENTER);
        llabel.setBackground(new java.awt.Color(255, 255, 255));
        llabel.setForeground(new java.awt.Color(255, 0, 0));
        llabel.setText("L");
        nirLabel.setBounds(20, 120, 250, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultRVI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(resultNDVI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(resultSAVI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(redLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(redField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nirField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(llabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(110, 180, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelqrq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelqrq, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(redLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(redField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nirField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(llabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultRVI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(resultNDVI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(resultSAVI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(616, 253));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        //verifica se ta vazio
        if (redField.getText().isEmpty() || nirField.getText().isEmpty()||lField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Valores das faixas de comprimento ou fator de ajuste nulos!!",
                    "Erro", JOptionPane.ERROR_MESSAGE);
            redField.setText("");
            nirField.setText("");
            lField.setText("");
            return;
        } else {
            if (evt.getSource() == btn) {
                double redValor = Double.parseDouble(redField.getText());
                double nirValor = Double.parseDouble(nirField.getText());
                double l = Double.parseDouble(lField.getText());
                // Verificar se os valores estão dentro das faixas corretas de comprimento de
                // onda
                if (redValor < 0.65 || redValor > 0.72 || nirValor < 0.72 || nirValor > 1.3) {
                    JOptionPane.showMessageDialog(this, "Valores fora das faixas de comprimento de onda permitidas.\nredValue < 0.65 || redValue > 0.72 || nirValue < 0.72 || nirValue > 1.3",
                            "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if (l<0 || l>1) {
                    JOptionPane.showMessageDialog(this, "Valores de L fora do fator de ajuste.\nfator de ajuste do solo (varia de 0 a 1)",
                            "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                // Cálculo dos índices de vegetação
                double rvi = redValor / nirValor;
                double ndvi = (nirValor - redValor) / (nirValor + redValor);
                double sav;
                double soma = nirValor + redValor + l;
                if (soma == 0) {
                    sav = 0;
                } else {
                    sav = (1 + l) * (nirValor - redValor) / soma;
                }
                //formatar pra 4 casas decimais
                String rvitxt = String.format("RVI: %.4f", rvi);
                String ndvitxt = String.format("NDVI: %.4f", ndvi);
                String savtxt = String.format("SAVI: %.4f", sav);
                // Exibir resultados
                resultRVI.setText(rvitxt);
                resultNDVI.setText(ndvitxt);
                resultSAVI.setText(savtxt);
            }
        }
    }//GEN-LAST:event_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndiceVegetacaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndiceVegetacaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndiceVegetacaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndiceVegetacaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndiceVegetacaoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn;
    private java.awt.TextField lField;
    private java.awt.Label labelqrq;
    private java.awt.Label llabel;
    private java.awt.TextField nirField;
    private java.awt.Label nirLabel;
    private java.awt.TextField redField;
    private java.awt.Label redLabel;
    private java.awt.Label resultNDVI;
    private java.awt.Label resultRVI;
    private java.awt.Label resultSAVI;
    // End of variables declaration//GEN-END:variables
}
