/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.conexaobanco;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author renan
 */
public class ConexaoDesoft extends javax.swing.JFrame {

    /**
     * Creates new form ConexaoDesoft
     */
    public ConexaoDesoft() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn = new javax.swing.JButton();
        porta = new javax.swing.JTextField();
        schema = new javax.swing.JTextField();
        USER = new javax.swing.JTextField();
        PASSWORD = new javax.swing.JTextField();
        URL = new javax.swing.JTextField();
        HOST = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco De Dados MySql - @Renan_Rodrigues");
        setBackground(new java.awt.Color(102, 102, 102));
        setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setFont(new java.awt.Font("Fira Code Light", 0, 12)); // NOI18N
        jLabel1.setText("URL completa");

        jLabel2.setBackground(new java.awt.Color(0, 0, 102));
        jLabel2.setFont(new java.awt.Font("Fira Code Light", 0, 12)); // NOI18N
        jLabel2.setText("Schema/DataBase");

        jLabel3.setBackground(new java.awt.Color(0, 0, 102));
        jLabel3.setFont(new java.awt.Font("Fira Code Light", 0, 12)); // NOI18N
        jLabel3.setText("Porta");

        jLabel4.setBackground(new java.awt.Color(0, 0, 102));
        jLabel4.setFont(new java.awt.Font("Fira Code Light", 0, 12)); // NOI18N
        jLabel4.setText("User");

        jLabel5.setBackground(new java.awt.Color(0, 0, 102));
        jLabel5.setFont(new java.awt.Font("Fira Code Light", 0, 12)); // NOI18N
        jLabel5.setText("Password");

        btn.setBackground(new java.awt.Color(0, 0, 0));
        btn.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btn.setForeground(new java.awt.Color(255, 255, 255));
        btn.setText("Conectar");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        porta.setBackground(new java.awt.Color(0, 0, 0));
        porta.setFont(new java.awt.Font("Fira Code Light", 0, 12)); // NOI18N
        porta.setForeground(new java.awt.Color(255, 255, 255));

        schema.setSize(90, 25);
        schema.setBackground(new java.awt.Color(0, 0, 0));
        schema.setFont(new java.awt.Font("Fira Code Light", 0, 12)); // NOI18N
        schema.setForeground(new java.awt.Color(255, 255, 255));

        USER.setSize(90, 25);
        USER.setBackground(new java.awt.Color(0, 0, 0));
        USER.setFont(new java.awt.Font("Fira Code Light", 0, 12)); // NOI18N
        USER.setForeground(new java.awt.Color(255, 255, 255));

        PASSWORD.setSize(90, 25);
        PASSWORD.setBackground(new java.awt.Color(0, 0, 0));
        PASSWORD.setFont(new java.awt.Font("Fira Code Light", 0, 12)); // NOI18N
        PASSWORD.setForeground(new java.awt.Color(255, 255, 255));

        URL.setSize(90, 25);
        URL.setBackground(new java.awt.Color(0, 0, 0));
        URL.setFont(new java.awt.Font("Fira Code Light", 0, 12)); // NOI18N
        URL.setForeground(new java.awt.Color(255, 255, 255));

        URL.setSize(90, 25);
        HOST.setBackground(new java.awt.Color(0, 0, 0));
        HOST.setFont(new java.awt.Font("Fira Code Light", 0, 12)); // NOI18N
        HOST.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(0, 0, 102));
        jLabel6.setFont(new java.awt.Font("Fira Code Light", 0, 12)); // NOI18N
        jLabel6.setText("HostName");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addComponent(btn)
                        .addGap(87, 87, 87)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(USER, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(porta, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PASSWORD, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(schema)))
                    .addComponent(HOST)
                    .addComponent(URL)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(137, 137, 137)))
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(URL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(9, 9, 9)
                .addComponent(HOST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(porta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(schema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(USER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(516, 328));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        btn.setText("Conectando...");
        //jdbc:mysql://host:porta/nome_database;
        final String usuario = USER.getText();
        final String senha = PASSWORD.getText();
        final String url = URL.getText();
        final String host = HOST.getText();
        final String db = schema.getText();
        final String port = porta.getText();
        if (!(url.isEmpty())) {
            porta.setText("");
            schema.setText("");
            HOST.setText("");
        } else {
            if (db.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Sinto muito.. precisamos de um schema para nos conectarmos!!", "Banco de Dados nulo", JOptionPane.ERROR_MESSAGE);
                btn.setText("Conectar");
                return;
            }
        }
        Connection cnx = cnx(usuario, senha, url, db, port, host);
        if (cnx
                != null) {
            String db_name = db;
            String portnum = port;
            String username = usuario;
            
            if (db.isEmpty()) {
                db_name = url.substring(url.lastIndexOf("/")+1);
            }
            if (port.isEmpty()) {
                portnum = "3306";
            }
            if (usuario.isEmpty()) {
                username = "root";
            }
            btn.setText("Conectado");

            JOptionPane.showMessageDialog(this, "Conectado com sucesso..."
                    + "\nBanco: " + db_name
                    + "\nUsuario: " + username
                    + "\nPorta: " + portnum
            );

        } else {
            btn.setText("Conectar");
            JOptionPane.showMessageDialog(null, "Algo deu errado!! verifique os campos corretamente");
            return;
        }
    }//GEN-LAST:event_btnActionPerformed
    static Connection cnx(String usuario, String senha, String url, String db, String port, String host) {
        String url_padrao = "jdbc:mysql://";
        String host_padrao = "localhost";
        String port_padrao = "3306";
        String user_padrao = "root";

        if (url.isEmpty()) {
            url = url_padrao;
            if (port.isEmpty()) {
                port = port_padrao;
            }
            if (host.isEmpty()) {
                host = host_padrao;
            }
            url = url + host + ":" + port + "/" + db;
        } else {
            url = url;
        }
        if (usuario.isEmpty()) {
            usuario = user_padrao;
        }

        System.out.println(url);
        Connection cnx = null;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            cnx = DriverManager.getConnection(url, usuario, senha);
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro no driver MySql");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao se conectar ao banco de dados MySql"
                    + "\nInsira um banco de dados ou uma senha validos!!!"
                    + "\n" + ex.getMessage());
        } finally {
            if (cnx != null) {
                try {
                    cnx.close();
                    System.out.println("Sucesso ao se desconectar!! ate logo " + usuario);
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Erro ao se desconectar do banco de dados MySql");
                }
            }
            return cnx;

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConexaoDesoft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConexaoDesoft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConexaoDesoft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConexaoDesoft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConexaoDesoft().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HOST;
    private javax.swing.JTextField PASSWORD;
    private javax.swing.JTextField URL;
    private javax.swing.JTextField USER;
    private javax.swing.JButton btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField porta;
    private javax.swing.JTextField schema;
    // End of variables declaration//GEN-END:variables
}
